#!/usr/bin/env python3
"""Writes docs/structure.md: every source file of the repo with the first
sentence of its own header comment, so the file list can't go stale.

Usage (from the repo root):
  .claude/scripts/structure.py           rewrite docs/structure.md
  .claude/scripts/structure.py --check   exit 1 if docs/structure.md is out of date
"""
import os
import re
import subprocess
import sys

OUT = "docs/structure.md"
# Not part of the shell: skipped in the listing.
SKIP = (".claude/", "docs/", "README.md", "CLAUDE.md", ".gitignore", ".gitattributes")
# What the folders hold, in the order shown.
ORDER = ["shell.qml", "config", "services", "components", "modules", "scripts", "matugen"]
INTRO = {
    "config": "Singletons for state and configuration. `*.json` files here are runtime state, git-ignored (Settings, Profiles, ThemeState, LocaleState, LauncherState, ChatAiState, GeneratedColors, NotificationActions).",
    "services": "Singletons wrapping system state and processes; most also hold an IPC target.",
    "components": "Generic building blocks shared by the widgets and panels (`import qs.components`).",
    "modules": "One directory per feature (`import qs.modules.<Name>`).",
    "scripts": "Python helpers the QML runs through `Process`.",
    "matugen": "Everything matugen: its config and every template it fills.",
}
# Files that can't carry a header comment (their output format has none), or
# whose first comment isn't about the file.
FALLBACK = {
    "shell.qml": "The shell root: instantiates every module and the services that must exist from startup.",
    "matugen/quickshell.toml": "The matugen config: the shell's palette and the other apps' colors (Hyprland, Zen, alacritty, GTK, Qt, starship).",
    "matugen/quickshell-theme.json.template": "Template of the shell's palette (written to config/GeneratedColors.json).",
    "matugen/hyprland-theme.lua.template": "Template of Hyprland's colors (~/.config/hypr/colors.lua).",
    "matugen/zen-theme.css.template": "Template coloring Zen browser.",
    "matugen/alacritty-theme.toml.template": "Template coloring alacritty.",
    "matugen/gtk-theme.css.template": "Template of the GTK named colors (libadwaita, and the olShell theme's).",
    "matugen/gtk3-theme-index.css.template": "The olShell GTK theme's GTK3 part (adw-gtk3-dark, or adw-gtk3 in light, plus the colors).",
    "matugen/gtk4-theme-index.css.template": "The olShell GTK theme's GTK4 part, for plain GTK4 apps.",
    "matugen/qt-colors.conf.template": "The olShell qt5ct / qt6ct color scheme, for Qt apps.",
    "matugen/starship-theme.toml.template": "Template of the starship prompt (~/.config/starship/starship.toml).",
}

HEADER = """## Structure

Generated by `.claude/scripts/structure.py` from each file's own header comment: don't edit it, change the comment in the file and run the script again.

Quickshell turns every directory into a QML module, so files are imported as `qs.<path>` (`import qs.config`, `import qs.services`, `import qs.components`, `import qs.modules.Bar.Widgets`), never by relative path.
"""


def files():
    out = subprocess.run(["git", "ls-files", "-co", "--exclude-standard"], capture_output=True, text=True, check=True).stdout
    return sorted({f for f in out.split("\n") if f and not f.startswith(SKIP) and os.path.isfile(f)})


def header(path):
    """The text of the file's first comment block, whitespace collapsed."""
    try:
        text = open(path, encoding="utf-8").read()
    except (OSError, UnicodeDecodeError):
        return ""
    if path.endswith(".py"):
        match = re.match(r'\s*(?:#![^\n]*\n)?\s*(?:"""(.*?)"""|((?:#[^\n]*\n)+))', text, re.S)
        if not match:
            return ""
        body = match.group(1) or "\n".join(line.lstrip("# ").rstrip() for line in match.group(2).split("\n"))
        return " ".join(body.split())
    marker = "//" if path.endswith(".qml") else "#"
    block, seen = [], False
    for line in text.split("\n"):
        stripped = line.strip()
        if stripped.startswith(marker) and not stripped.startswith("//@"):
            block.append(stripped[len(marker):].strip())
            seen = True
        elif seen:
            break
        elif not stripped or stripped.startswith(("import", "pragma", "//@")) or (marker == "#" and stripped.startswith("#!")):
            continue
        else:
            break
    return " ".join(" ".join(block).split())


def summary(text, limit=140):
    """The first sentence, cut at a word if it is still too long."""
    text = re.sub(r"\b(e\.g|i\.e|etc)\.", r"\1․", text)
    match = re.match(r"(.+?\.)(\s|$)", text)
    sentence = match.group(1) if match else text
    sentence = sentence.rstrip(":;,").replace("․", ".")
    if len(sentence) > limit:
        sentence = sentence[:limit].rsplit(" ", 1)[0].rstrip(",;:") + "…"
    return sentence


def render():
    groups = {}
    for path in files():
        groups.setdefault(os.path.dirname(path), []).append(path)
    lines = [HEADER]
    for top in ORDER:
        if top == "shell.qml":
            if "shell.qml" in files():
                lines.append(f"- [`shell.qml`](../shell.qml): {FALLBACK['shell.qml']}\n")
            continue
        for directory in sorted(d for d in groups if d == top or d.startswith(top + "/")):
            lines.append(f"### {directory}/\n")
            if directory == top and top in INTRO:
                lines.append(INTRO[top] + "\n")
            for path in groups[directory]:
                text = FALLBACK.get(path) or summary(header(path))
                lines.append(f"- [`{os.path.basename(path)}`](../{path})" + (f": {text}" if text else ""))
            lines.append("")
    lines.append("### Not part of the shell\n")
    lines.append("- `.claude/`: Claude Code skills and the check scripts; left out of the deploy (see `.gitattributes`).")
    lines.append("- `docs/`: this documentation.")
    return "\n".join(lines).rstrip("\n") + "\n"


if __name__ == "__main__":
    text = render()
    if "--check" in sys.argv:
        current = open(OUT, encoding="utf-8").read() if os.path.isfile(OUT) else ""
        if current != text:
            print(f"{OUT} is out of date: run .claude/scripts/structure.py")
            sys.exit(1)
        print(f"{OUT} is up to date")
    else:
        os.makedirs("docs", exist_ok=True)
        open(OUT, "w", encoding="utf-8").write(text)
        print(f"wrote {OUT}: {text.count(chr(10))} lines")
