pragma Singleton

import Quickshell

// The built-in ("factory") value of every setting: what Settings.qml uses when
// nothing has been saved, and what the settings panel's Factory buttons put
// back. Nothing writes to this file; the user's own defaults, saved from the
// panel, are in UserDefaults.json (see Settings.qml).
Singleton {
  readonly property var values: ({
    radius: 5,
    opacity: 0.9,
    spacing: 15,
    barAutoHide: false,
    barAutoHideAnimated: true,
    barAutoHideDuration: 150,
    barAutoHideDelay: 500,
    barPosition: "top",
    barHeight: 40,
    barMarginTop: 5,
    barMarginBottom: 0,
    barMarginLeft: 5,
    barMarginRight: 5,
    panelGap: 0,
    curvedJoins: true,
    curvedJoinsRadius: 5,
    curvedJoinsRadiusSame: true,
    workspaceCount: 5,
    workspaceCountFromHyprland: false,
    barStyle: "widgets",
    borderWidth: 2,
    borderOpaque: false,
    blur: false,
    blurSize: 3,
    blurPasses: 3,
    blurNoise: 0.0117,
    blurContrast: 0.8916,
    blurBrightness: 1,
    blurVibrancy: 0.1696,
    blurXray: false,
    windowBorderWidth: 2,
    windowBorderSame: false,
    windowRounding: 10,
    windowRoundingSame: false,
    windowGapsIn: 3,
    windowGapsInSame: false,
    windowGapsOut: 5,
    windowActiveOpacity: 1,
    windowInactiveOpacity: 1,
    zoomBlocksInput: false,
    zoomMax: 8,
    zoomStep: 0.5,
    fontSize: 18,
    fontFamily: "0xProto Nerd Font",
    fontWeight: 400,
    fontLetterSpacing: 0,
    fontCaps: "none",
    fontItalic: false,
    fontUnderline: false,
    fontOutline: false,
    wallpaperTransition: "fade",
    wallpaperDuration: 2,
    matugenScheme: "tonal-spot",
    matugenSource: "saturation",
    matugenContrast: 0,
    themeMode: "dark",
    matugenLightness: 0,
    matugenAccent: "primary",
    themePill: "normal",
    matugenHyprland: true,
    matugenZen: true,
    matugenAlacritty: true,
    matugenGtk: true,
    matugenQt: true,
    matugenStarship: true,
    matugenApps: [],
    themeAccent: "default",
    themeExactApps: true,
    customBackground: "#1e1e2e",
    customPill: "#313244",
    customBorder: "#45475a",
    customText: "#cdd6f4",
    customAccent: "#89b4fa",
    screenshotMode: "screen",
    screenshotEdit: false,
    screenshotDir: Quickshell.env("HOME") + "/Pictures/Screenshots",
    notificationTimeout: 6,
    notificationMax: 4,
    notificationDnd: false,
    notificationPosition: "top-right",
    volumeOsdPosition: "bottom-center",
    volumeOsdMargin: 60,
    lockKeysOsdPosition: "bottom-center",
    lockKeysOsdMargin: 60,
    lockTimeout: 10,
    launcherTab: "all",
    launcherPlacement: "center",
    settingsPlacement: "center",
    shortcutsPlacement: "center",
    wallpaperPlacement: "bar-center",
    themePlacement: "bar-center",
    powerPlacement: "bar-center",
    notificationActionsPlacement: "center",
    switcherPlacement: "center",
    clockPlacement: "bar-center",
    notificationCenterPlacement: "bar-center",
    switcherOrientation: "vertical",
    switcherScope: "all",
    switcherGroupApps: false,
    switcherShowTitle: true,
    switcherShowApp: true,
    switcherShowWorkspace: true,
    switcherIconSize: 40,
    switcherMaxShown: 8,
    switcherReleaseSwitch: true,
    switcherPreviews: false,
    clockShowAgenda: true,
    clockShowPerformance: true,
    clockShowMedia: true,
    clockShowWeather: true,
    clockShowWorld: true,
    worldClocks: [],
    weatherUnit: "celsius",
    weatherLocation: "",
    clockDate: "long",
    clockSeconds: true,
    cpuRing: false,
    ramRing: false,
    diskRing: false,
    volumeRing: false,
    networkRing: false,
    activeWindowIconOnly: false,
    launcherResults: 7,
    launcherEngines: [
      { browser: true, on: true },
      { name: "YouTube", url: "https://www.youtube.com/results?search_query=%s", on: true },
      { name: "Wikipedia", url: "https://fr.wikipedia.org/w/index.php?search=%s", on: true }
    ],
    barCollapsed: [],
    barGroupsOff: [],
    barLeft: ["launcher", "settings", "workspaces", "activeWindow"],
    barCenter: ["clock", "wallpaper", "theme", "screenshot", "zoom", "shortcuts"],
    barRight: ["tray", "cpu", "ram", "disk", "network", "connection", "bluetooth", "volume", "notifications", "lock", "power"],
    barDividers: ["workspaces", "activeWindow", "wallpaper", "cpu", "ram", "disk", "network", "connection", "bluetooth", "volume", "notifications", "lock"]
    })
}
