pragma Singleton

import Quickshell

// The built-in ("factory") value of every setting: what Settings.qml uses when
// nothing has been saved, and what the Factory profile (see
// services/Profiles.qml) puts back. Nothing writes to this file.
Singleton {
  readonly property var values: ({
    radius: 10,
    opacity: 0.9,
    spacing: 15,
    barAutoHide: false,
    animations: true,
    animationDuration: 160,
    hyprlandAnimations: true,
    hyprlandAnimationDuration: 1,
    hyprlandAnimationSame: true,
    hyprlandWindowStyle: "gnomed",
    hyprlandWorkspaceStyle: "slide",
    barAutoHideDelay: 500,
    barPosition: "top",
    barHeight: 40,
    barMarginTop: 5,
    barMarginBottom: 0,
    barMarginLeft: 5,
    barMarginRight: 5,
    panelGap: 0,
    curvedJoins: true,
    curvedJoinsRadius: 20,
    curvedJoinsRadiusSame: false,
    workspaceCount: 14,
    workspaceCountFromHyprland: true,
    barStyle: "full",
    borderWidth: 0,
    borderOpaque: false,
    blur: true,
    blurSize: 3,
    blurPasses: 3,
    blurNoise: 0.0117,
    blurContrast: 0.8916,
    blurBrightness: 1,
    blurVibrancy: 0.1696,
    blurXray: false,
    windowBorderWidth: 2,
    windowBorderSame: false,
    windowRounding: 8,
    windowRoundingSame: true,
    windowActiveOpacitySame: true,
    windowInactiveOpacitySame: true,
    windowGapsIn: 3,
    windowGapsInSame: false,
    windowGapsOut: 5,
    windowActiveOpacity: 1,
    windowInactiveOpacity: 1,
    appOpacities: [
      { class: "Alacritty", active: 0.95, inactive: 1, activeSame: false, inactiveSame: true }
    ],
    zoomBlocksInput: false,
    zoomMax: 8,
    zoomStep: 0.5,
    fontSize: 18,
    fontFamily: "0xProto Nerd Font",
    fontWeight: 400,
    fontLetterSpacing: 0,
    fontCaps: "none",
    fontItalic: false,
    fontUnderline: false,
    fontOutline: false,
    wallpaperTransition: "fade",
    wallpaperDuration: 2,
    wallpaperCarousel: "gentle",
    wallpaperSideCount: 3,
    themeCarousel: "gentle",
    themeSideCount: 3,
    matugenScheme: "tonal-spot",
    matugenSource: "saturation",
    matugenContrast: 0,
    themeMode: "dark",
    matugenLightness: 0,
    matugenAccent: "primary",
    themePill: "normal",
    matugenHyprland: true,
    matugenZen: true,
    matugenAlacritty: true,
    matugenGtk: true,
    matugenQt: true,
    matugenStarship: true,
    matugenApps: [],
    themeAccent: "default",
    themeExactApps: true,
    customBackground: "#968c95",
    customPill: "#313244",
    customBorder: "#45475a",
    customText: "#cdd6f4",
    customAccent: "#89b4fa",
    screenshotMode: "region",
    screenshotEdit: false,
    screenshotDir: Quickshell.env("HOME") + "/Pictures/Screenshots",
    notificationTimeout: 4,
    notificationMax: 4,
    notificationDnd: false,
    notificationPosition: "top-center",
    osdPosition: "bottom-center",
    osdMargin: 60,
    volumeOsdSame: true,
    volumeOsdPosition: "bottom-center",
    volumeOsdMargin: 60,
    lockKeysOsdPosition: "bottom-right",
    lockKeysOsdMargin: 60,
    lockKeysOsdSame: false,
    lockTimeout: 8,
    lockStayAwakeFullscreen: true,
    launcherTab: "all",
    launcherPlacement: "bar-center",
    settingsPlacement: "bar-center",
    shortcutsPlacement: "bar-center",
    wallpaperPlacement: "bar-center",
    themePlacement: "bar-center",
    powerPlacement: "bar-center",
    notificationActionsPlacement: "bar-center",
    switcherPlacement: "bar-center",
    clockPlacement: "bar-center",
    notificationCenterPlacement: "bar-center",
    chatAiPlacement: "bar-center",
    switcherOrientation: "horizontal",
    switcherScope: "all",
    switcherGroupApps: true,
    switcherShowTitle: true,
    switcherShowApp: true,
    switcherShowWorkspace: true,
    switcherIconSize: 64,
    switcherMaxShown: 10,
    switcherReleaseSwitch: true,
    switcherPreviews: false,
    clockShowAgenda: true,
    clockShowPerformance: true,
    clockShowMedia: true,
    clockShowWeather: true,
    clockShowWorld: true,
    worldClocks: [],
    weatherUnit: "celsius",
    weatherLocation: "",
    clockDate: "long",
    clockSeconds: false,
    cpuLayout: "vertical",
    ramLayout: "vertical",
    diskLayout: "vertical",
    volumeLayout: "vertical",
    networkLayout: "vertical",
    activeWindowLayout: "auto",
    launcherResults: 10,
    launcherHistory: 3,
    launcherEngines: [
      { browser: true, on: true },
      { name: "YouTube", url: "https://www.youtube.com/results?search_query=%s", on: true },
      { name: "Wikipedia", url: "https://fr.wikipedia.org/w/index.php?search=%s", on: true }
    ],
    webApps: [],
    webAppCommand: "zen-browser -P webapp --new-window %s",
    cpuAction: "btop",
    cpuActionTerminal: true,
    cpuActionFloating: true,
    ramAction: "btop",
    ramActionTerminal: true,
    ramActionFloating: true,
    diskAction: "gdu --no-cross /",
    diskActionTerminal: true,
    diskActionFloating: true,
    networkAction: "btop",
    networkActionTerminal: true,
    networkActionFloating: true,
    connectionAction: "nm-connection-editor",
    connectionActionTerminal: false,
    connectionActionFloating: false,
    bluetoothAction: "blueman-manager",
    bluetoothActionTerminal: false,
    bluetoothActionFloating: false,
    chatAiProviders: [
      { builtin: "anthropic", model: "" },
      { builtin: "openai", model: "" },
      { builtin: "xai", model: "" },
      { builtin: "google", model: "" }
    ],
    chatAiListDir: true,
    chatAiFindFiles: true,
    chatAiSearchText: true,
    chatAiReadFile: true,
    chatAiWebSearch: true,
    chatAiWebFetch: true,
    chatAiShellDocs: true,
    chatAiShellIpc: false,
    chatAiFolders: "",
    chatAiExclude: "",
    chatAiHistory: 50,
    chatAiDefaultProvider: "",
    chatAiShowUsage: true,
    chatAiShowHint: true,
    chatAiShowAccess: true,
    barCollapsed: ["wallpaper"],
    barGroupsOff: [],
    barDisabled: [],
    barLeft: ["webApps", "launcher", "settings", "workspaces", "activeWindow", "wallpaper", "theme", "zoom", "screenshot", "shortcuts"],
    barCenter: ["clock", "volume"],
    barRight: ["tray", "cpu", "ram", "disk", "network", "connection", "bluetooth", "notifications", "power"],
    barDividers: ["workspaces", "activeWindow", "wallpaper", "volume", "cpu", "ram", "disk", "network", "connection", "notifications", "power"]
    })
}
