pragma Singleton

import Quickshell

// Filesystem locations used by the shell, derived from the shell's own
// directory and the user's XDG config dir so nothing is tied to one
// machine or username. Edit here to move where wallpapers or the matugen
// config live.
Singleton {
  readonly property string userConfigDir: Quickshell.env("XDG_CONFIG_HOME") || (Quickshell.env("HOME") + "/.config")

  // Regenerated by matugen (see GeneratedColors.json.template).
  readonly property string generatedColors: Quickshell.shellPath("config/GeneratedColors.json")

  readonly property string wallpaperDir: userConfigDir + "/wallpapers/bing/saved"
  readonly property string wallpaperOfTheDay: userConfigDir + "/wallpapers/bing/pod.jpg"

  // The selected theme, remembered across restarts (git-ignored).
  readonly property string themeState: Quickshell.shellPath("config/ThemeState.json")

  // The adjustable look-and-feel values (git-ignored).
  readonly property string settings: Quickshell.shellPath("config/Settings.json")

  // The chosen language, remembered across restarts (git-ignored).
  readonly property string localeState: Quickshell.shellPath("config/LocaleState.json")

  // Dedicated matugen config containing only this shell's templates, kept in
  // the repo so nothing has to be copied into ~/.config/matugen.
  readonly property string matugenConfig: Quickshell.shellPath("matugen/quickshell.toml")
}
