pragma Singleton

import Quickshell

// Filesystem locations used by the shell, derived from the shell's own
// directory and the user's XDG config dir so nothing is tied to one
// machine or username. Edit here to move where wallpapers or the matugen
// config live.
Singleton {
  readonly property string userConfigDir: Quickshell.env("XDG_CONFIG_HOME") || (Quickshell.env("HOME") + "/.config")

  // Regenerated by matugen (see matugen/quickshell-theme.json.template).
  readonly property string generatedColors: Quickshell.shellPath("config/GeneratedColors.json")

  readonly property string wallpaperDir: userConfigDir + "/wallpapers/bing/saved"
  readonly property string wallpaperOfTheDay: userConfigDir + "/wallpapers/bing/pod.jpg"

  // The selected theme, remembered across restarts (git-ignored).
  readonly property string themeState: Quickshell.shellPath("config/ThemeState.json")

  // The adjustable look-and-feel values (git-ignored).
  readonly property string settings: Quickshell.shellPath("config/Settings.json")
  // The values the user saved as their own defaults (see Settings.qml).
  readonly property string userDefaults: Quickshell.shellPath("config/UserDefaults.json")
  // The notification actions (see NotificationActions.qml); like the two
  // above, only there once something has been saved.
  readonly property string notificationActions: Quickshell.shellPath("config/NotificationActions.json")

  // The chosen language, remembered across restarts (git-ignored).
  readonly property string localeState: Quickshell.shellPath("config/LocaleState.json")

  // The script that takes screenshots (the folder they go to is a setting).
  readonly property string screenshotScript: Quickshell.shellPath("scripts/screenshot.py")

  // Applies a wallpaper with awww, starting its daemon if needed.
  readonly property string applyWallpaperScript: Quickshell.shellPath("scripts/apply-wallpaper.py")

  // Lists the Hyprland config's shortcuts, for the shortcuts panel.
  readonly property string listShortcutsScript: Quickshell.shellPath("scripts/list-shortcuts.py")

  // Dedicated matugen config, kept in the repo so nothing has to be copied
  // into ~/.config/matugen: the shell's palette and the other apps' colors.
  readonly property string matugenConfig: Quickshell.shellPath("matugen/quickshell.toml")
}
