pragma Singleton

import Quickshell
import QtQuick

// Shared visual constants for the shell. Import via `qs.config`.
Singleton {
  // Adjustable from the settings panel (see Settings.qml).
  readonly property int barHeight: Settings.barHeight
  readonly property int barMarginLeft: Settings.barMarginLeft
  readonly property int barMarginRight: Settings.barMarginRight
  readonly property int barMarginTop: Settings.barMarginTop
  readonly property int barMarginBottom: Settings.barMarginBottom
  // Colors below come from GeneratedColors.qml, regenerated by matugen
  // from the current wallpaper (see matugen/quickshell-theme.json.template and
  // WallpaperPanel.qml's apply()).
  readonly property color backgroundColor: GeneratedColors.backgroundColor
  readonly property color borderColor: GeneratedColors.borderColor
  readonly property color textColor: GeneratedColors.textColor
  readonly property color accentColor: GeneratedColors.accentColor
  readonly property color pillColor: GeneratedColors.pillColor
  readonly property color outlineColor: outlineOf(pillColor, textColor)
  // For values that need attention (a nearly full disk, a saturated CPU).
  readonly property color warningColor: "#f38ba8"
  readonly property color separatorColor: Qt.darker(textColor, 1.3)
  readonly property string fontFamily: Settings.fontFamily
  readonly property int fontWeight: Settings.fontWeight
  readonly property real fontLetterSpacing: Settings.fontLetterSpacing
  // Settings.fontCaps as the font's capitalization.
  readonly property int fontCapitalization: ({
    none: Font.MixedCase,
    upper: Font.AllUppercase,
    lower: Font.AllLowercase,
    small: Font.SmallCaps
  })[Settings.fontCaps]
  readonly property bool fontItalic: Settings.fontItalic
  readonly property bool fontUnderline: Settings.fontUnderline
  readonly property bool fontOutline: Settings.fontOutline
  readonly property int pillPadding: 15
  readonly property real widgetOpacity: Settings.opacity
  readonly property real widgetSpacing: Settings.spacing
  // Corner radius for every rounded item (pills, panels, dialogs, cards,
  // buttons, dots...). Items use radiusFor() so a radius larger than half
  // an item's size just makes it fully round instead of distorting it.
  readonly property int radius: Settings.radius
  // Width of the outline drawn around surfaces (pills, popups, panels,
  // dialogs, cards, the OSD), in Theme.outlineColor so it follows the theme.
  // 0 turns borders off.
  readonly property int borderWidth: Settings.borderWidth
  // How far the border color is pulled from the surface color toward the
  // text color (0 = same as the surface, 1 = the text color). Deriving it
  // from the theme's own colors keeps the outline visible on every palette.
  readonly property real borderContrast: 0.35
  

  // Border color for a surface of color `surface` with text color `text`
  // (any color values, e.g. a theme preview's).
  function outlineOf(surface, text) {
    const fg = Qt.color(text)
    return Qt.tint(Qt.color(surface), Qt.rgba(fg.r, fg.g, fg.b, borderContrast))
  }

  function radiusFor(size) {
    return Math.min(radius, size / 2)
  }

  // Height of the pill containers grouping each bar section - always
  // matches the bar's own height so widgets fill it edge to edge.
  function pillHeight() {
    return barHeight
  }

  // Square size for tray icons and the active window's icon, derived from the
  // font size so they stay proportional to the text next to them (20 px at
  // the default 18 px font).
  function trayIconSize() {
    return Math.round(fontSize() * 1.1)
  }

  // Text size in pixels, from the settings; every text scales from it.
  function fontSize() {
    return Settings.fontSize
  }
}
