pragma Singleton

import Quickshell
import QtQuick

// Shared visual constants for the shell. Import via `qs.config`.
Singleton {
  // Adjustable from the settings panel (see Settings.qml).
  readonly property int barHeight: Settings.barHeight
  readonly property int barMarginLeft: Settings.barMarginLeft
  readonly property int barMarginRight: Settings.barMarginRight
  readonly property int barMarginTop: Settings.barMarginTop
  // Colors below come from GeneratedColors.qml, regenerated by matugen
  // from the current wallpaper (see matugen/GeneratedColors.json.template and
  // WallpaperPanel.qml's apply()).
  readonly property color backgroundColor: GeneratedColors.backgroundColor
  readonly property color borderColor: GeneratedColors.borderColor
  readonly property color textColor: GeneratedColors.textColor
  readonly property color accentColor: GeneratedColors.accentColor
  readonly property color pillColor: GeneratedColors.pillColor
  readonly property color outlineColor: outlineOf(pillColor, textColor)
  // For values that need attention (a nearly full disk, a saturated CPU).
  readonly property color warningColor: "#f38ba8"
  readonly property color separatorColor: Qt.darker(textColor, 1.3)
  readonly property string fontFamily: "0xProto Nerd Font"
  readonly property int pillPadding: 15
  readonly property real widgetOpacity: Settings.opacity
  readonly property real widgetSpacing: Settings.spacing
  // Corner radius for every rounded item (pills, panels, dialogs, cards,
  // buttons, dots...). Items use radiusFor() so a radius larger than half
  // an item's size just makes it fully round instead of distorting it.
  readonly property int radius: Settings.radius
  // Width of the outline drawn around surfaces (pills, popups, panels,
  // dialogs, cards, the OSD), in Theme.outlineColor so it follows the theme.
  // 0 turns borders off.
  readonly property int borderWidth: Settings.borderWidth
  // How far the border color is pulled from the surface color toward the
  // text color (0 = same as the surface, 1 = the text color). Deriving it
  // from the theme's own colors keeps the outline visible on every palette.
  readonly property real borderContrast: 0.35
  

  // Border color for a surface of color `surface` with text color `text`
  // (any color values, e.g. a theme preview's).
  function outlineOf(surface, text) {
    const fg = Qt.color(text)
    return Qt.tint(Qt.color(surface), Qt.rgba(fg.r, fg.g, fg.b, borderContrast))
  }

  function radiusFor(size) {
    return Math.min(radius, size / 2)
  }

  // Height of the pill containers grouping each bar section - always
  // matches the bar's own height so widgets fill it edge to edge.
  function pillHeight() {
    return barHeight
  }

  // Square size for tray icons, derived from barHeight so they stay
  // proportional if it changes.
  function trayIconSize() {
    return Math.round(barHeight * 0.5)
  }

  // Text size for bar widgets, derived from barHeight so every widget
  // scales together when it changes.
  function fontSize() {
    return Math.round(barHeight * 0.45)
  }
}
