#!/usr/bin/env python3
"""Starts btop in a terminal, themed with the shell's colors.

Usage: btop-launch.py --background #rrggbb --surface #rrggbb --text #rrggbb
                      --accent #rrggbb --outline #rrggbb -- TERMINAL...

TERMINAL... is the terminal command up to, but not including, the `-e btop`
part, which is added here. A btop theme is generated from the colors into
$XDG_RUNTIME_DIR/quickshell-btop/, along with a copy of your btop.conf that
selects it, so your own btop configuration is left alone (settings changed
inside this btop are saved to the copy, not to your file).
"""
import argparse
import os
import re

parser = argparse.ArgumentParser()
for name in ("background", "surface", "text", "accent", "outline"):
    parser.add_argument("--" + name, required=True)
parser.add_argument("terminal", nargs=argparse.REMAINDER)
args = parser.parse_args()
terminal = args.terminal[1:] if args.terminal[:1] == ["--"] else args.terminal


def rgb(color):
    return [int(color[i:i + 2], 16) for i in (1, 3, 5)]


def blend(color, into, amount):
    """`color` moved `amount` of the way toward `into`."""
    return "#%02x%02x%02x" % tuple(round(a + (b - a) * amount) for a, b in zip(rgb(color), rgb(into)))


surface, text, accent = args.surface, args.text, args.accent


def ramp(color):
    """A meter/graph gradient: dim, normal, bright."""
    return blend(color, surface, 0.5), color, blend(color, text, 0.4)


theme = {
    "main_bg": surface,
    "main_fg": text,
    "title": text,
    "hi_fg": accent,
    "selected_bg": accent,
    "selected_fg": args.background,
    "inactive_fg": blend(text, surface, 0.55),
    "proc_misc": accent,
    "cpu_box": args.outline,
    "mem_box": args.outline,
    "net_box": args.outline,
    "proc_box": args.outline,
    "div_line": args.outline,
}
groups = {
    "temp": ramp(accent),
    "cpu": ramp(accent),
    "free": (blend(accent, surface, 0.7), blend(accent, surface, 0.6), blend(accent, surface, 0.5)),
    "cached": ramp(blend(accent, text, 0.3)),
    "available": ramp(accent),
    "used": ramp(blend(accent, text, 0.75)),
    "download": ramp(accent),
    "upload": ramp(blend(accent, text, 0.5)),
}
for group, (start, mid, end) in groups.items():
    theme[group + "_start"], theme[group + "_mid"], theme[group + "_end"] = start, mid, end

runtime = os.path.join(os.environ.get("XDG_RUNTIME_DIR") or "/tmp", "quickshell-btop")
themes_dir = os.path.join(runtime, "themes")
os.makedirs(themes_dir, exist_ok=True)

with open(os.path.join(themes_dir, "quickshell.theme"), "w") as f:
    f.write("# Generated by btop-launch.py from the Quickshell theme.\n")
    for key, value in theme.items():
        f.write('theme[%s]="%s"\n' % (key, value))

# The user's config, with our theme selected (and its background painted).
config_home = os.environ.get("XDG_CONFIG_HOME") or os.path.expanduser("~/.config")
try:
    with open(os.path.join(config_home, "btop", "btop.conf")) as f:
        config = f.read()
except OSError:
    config = ""
for key, value in (("color_theme", '"quickshell"'), ("theme_background", "true")):
    line = "%s = %s" % (key, value)
    config, replaced = re.subn(r"(?m)^%s\s*=.*$" % key, line, config)
    if not replaced:
        config += ("" if config.endswith("\n") or not config else "\n") + line + "\n"
config_path = os.path.join(runtime, "btop.conf")
with open(config_path, "w") as f:
    f.write(config)

# Terminal colors too: btop covers the whole window, but the padding around
# it shows the terminal's own background.
extra = []
if os.path.basename(terminal[0]) == "alacritty":
    for key, value in (
        ("colors.primary.background", '"%s"' % surface),
        ("colors.primary.foreground", '"%s"' % text),
        ("colors.cursor.cursor", '"%s"' % accent),
        ("window.decorations", '"None"'),
        ("window.padding", "{x=12,y=8}"),
    ):
        extra += ["-o", "%s=%s" % (key, value)]

command = terminal + extra + ["-e", "btop", "--config", config_path, "--themes-dir", themes_dir]
os.execvp(command[0], command)
