#!/usr/bin/env python3
"""Starts a TUI application (btop or gdu) in a terminal, themed with the shell's colors.

Usage: tui-launch.py --app btop|gdu --background #rrggbb --surface #rrggbb
                     --text #rrggbb --accent #rrggbb --outline #rrggbb
                     --warning #rrggbb --opacity 0-1 [--boxes "net"] [--set KEY=VALUE]... -- TERMINAL...

TERMINAL... is the terminal command up to, but not including, the `-e APP`
part, which is added here. A theme is generated from the colors into
$XDG_RUNTIME_DIR/quickshell-APP/, along with a copy of your own configuration
file for the application that selects it, so your own configuration is left
alone (settings changed inside the application are saved to the copy, not to
your file). gdu is given a
configuration file of its own (you have none by default) with the styles set.
--boxes (btop only) is the list of boxes to show, e.g. "net" or "cpu mem"
(btop's `shown_boxes`), instead of the ones in your configuration. --set (btop
only, repeatable) overrides any other btop setting the same way, e.g.
`--set show_disks=False`.

The terminal window is made as translucent as the shell's widgets (--opacity),
so the compositor can blur what's behind it: the applications are themed but
don't paint a background of their own, the terminal's shows through.
"""
import argparse
import os
import re

parser = argparse.ArgumentParser()
parser.add_argument("--app", required=True, choices=("btop", "gdu"))
for name in ("background", "surface", "text", "accent", "outline", "warning"):
    parser.add_argument("--" + name, required=True)
parser.add_argument("--opacity", type=float, default=1.0)
parser.add_argument("--boxes", default="")
parser.add_argument("--set", action="append", default=[], metavar="KEY=VALUE")
parser.add_argument("terminal", nargs=argparse.REMAINDER)
args = parser.parse_args()
terminal = args.terminal[1:] if args.terminal[:1] == ["--"] else args.terminal


def rgb(color):
    return [int(color[i:i + 2], 16) for i in (1, 3, 5)]


def blend(color, into, amount):
    """`color` moved `amount` of the way toward `into`."""
    return "#%02x%02x%02x" % tuple(round(a + (b - a) * amount) for a, b in zip(rgb(color), rgb(into)))


surface, text, accent = args.surface, args.text, args.accent


def ramp(color):
    """A meter/graph gradient: dim, normal, bright."""
    return blend(color, surface, 0.5), color, blend(color, text, 0.4)


def read_user_config(*parts):
    """The contents of ~/.config/<parts>, or "" if there is no such file."""
    config_home = os.environ.get("XDG_CONFIG_HOME") or os.path.expanduser("~/.config")
    try:
        with open(os.path.join(config_home, *parts)) as f:
            return f.read()
    except OSError:
        return ""


runtime = os.path.join(os.environ.get("XDG_RUNTIME_DIR") or "/tmp", "quickshell-" + args.app)
os.makedirs(runtime, exist_ok=True)


def btop():
    """Writes btop's theme and configuration; returns its command line."""
    theme = {
        "main_bg": surface,
        "main_fg": text,
        "title": text,
        "hi_fg": accent,
        "selected_bg": accent,
        "selected_fg": args.background,
        "inactive_fg": blend(text, surface, 0.55),
        "proc_misc": accent,
        "cpu_box": args.outline,
        "mem_box": args.outline,
        "net_box": args.outline,
        "proc_box": args.outline,
        "div_line": args.outline,
    }
    groups = {
        "temp": ramp(accent),
        "cpu": ramp(accent),
        "free": (blend(accent, surface, 0.7), blend(accent, surface, 0.6), blend(accent, surface, 0.5)),
        "cached": ramp(blend(accent, text, 0.3)),
        "available": ramp(accent),
        "used": ramp(blend(accent, text, 0.75)),
        "download": ramp(accent),
        "upload": ramp(blend(accent, text, 0.5)),
    }
    for group, (start, mid, end) in groups.items():
        theme[group + "_start"], theme[group + "_mid"], theme[group + "_end"] = start, mid, end

    themes_dir = os.path.join(runtime, "themes")
    os.makedirs(themes_dir, exist_ok=True)

    with open(os.path.join(themes_dir, "quickshell.theme"), "w") as f:
        f.write("# Generated by tui-launch.py from the Quickshell theme.\n")
        for key, value in theme.items():
            f.write('theme[%s]="%s"\n' % (key, value))

    # The user's config, with our theme selected (and its background left to
    # the terminal, so the window can be translucent).
    config = read_user_config("btop", "btop.conf")
    settings = [("color_theme", '"quickshell"'), ("theme_background", "false")]
    if args.boxes:
        settings.append(("shown_boxes", '"%s"' % args.boxes.replace('"', "")))
    settings += [tuple(item.split("=", 1)) for item in args.set if "=" in item]
    for key, value in settings:
        line = "%s = %s" % (key, value)
        config, replaced = re.subn(r"(?m)^%s\s*=.*$" % key, line, config)
        if not replaced:
            config += ("" if config.endswith("\n") or not config else "\n") + line + "\n"
    config_path = os.path.join(runtime, "btop.conf")
    with open(config_path, "w") as f:
        f.write(config)
    return ["btop", "--config", config_path, "--themes-dir", themes_dir]


def gdu():
    """Writes gdu's configuration with our styles; returns its command line: the
    disk mounted on / (without crossing to other filesystems), analyzed."""
    def colors(**fields):
        return "{ " + ", ".join("%s: '%s'" % (key.replace("_", "-"), value) for key, value in fields.items()) + " }"

    config = "\n".join((
        "# Generated by tui-launch.py from the Quickshell theme.",
        "style:",
        "  header: " + colors(text_color=args.background, background_color=accent),
        "  footer: " + colors(text_color=args.background, background_color=accent, number_color=args.background),
        "  selected-row: " + colors(text_color=args.background, background_color=accent),
        "  marked: " + colors(text_color=args.background, background_color=args.warning),
        "  result-row: " + colors(number_color=text, directory_color=accent),
        "",
    ))
    config_path = os.path.join(runtime, "gdu.yaml")
    with open(config_path, "w") as f:
        f.write(config)
    return ["gdu", "--config-file", config_path, "--no-cross", "/"]


# Terminal colors too: the applications leave their background to the
# terminal (btop's `theme_background` is off), and so does
# the padding around them. The window's opacity is the shell's.
extra = []
if os.path.basename(terminal[0]) == "alacritty":
    for key, value in (
        ("colors.primary.background", '"%s"' % surface),
        ("colors.primary.foreground", '"%s"' % text),
        ("colors.cursor.cursor", '"%s"' % accent),
        ("window.decorations", '"None"'),
        ("window.opacity", "%.2f" % max(0.0, min(1.0, args.opacity))),
        ("window.padding", "{x=12,y=8}"),
    ):
        extra += ["-o", "%s=%s" % (key, value)]

command = terminal + extra + ["-e"] + {"btop": btop, "gdu": gdu}[args.app]()
os.execvp(command[0], command)
